### ISSUE TITLE
Dataset pre-processing script

### ISSUE THREAD

**Issue by ZiYang-xie** [aimagelab/mcmr#1]
Hi, Thanks for sharing this great work. 
Can you provide the script for dataset pre-processing?

**Comment by alexj94** [comment]
Hi @ZiYang-xie,
thanks for your interest in our work.
We are currently working on releasing the remaining information in a few days.

**Comment by alexj94** [comment]
As promised, we finally released all the necessary information for reproducing all paper experiments. I hope everything is clear. If you have any questions, please open another issue.
