### ISSUE TITLE
Cycle import in File datasets/pascal3d/preprocess.py

### ISSUE THREAD

**Issue by hzykent** [aimagelab/mcmr#2]
Thank you for sharing your amazing work!

I found a cycle import issue in file datasets/pascal3d/preprocess.py. It imports modules from other files that import modules from it. This will result in several ImportErrors. I found that simply restructuring the files would be a quick fix.

Cheers~

**Comment by alexj94** [comment]
Hi @hzykent,
thanks for the interest in our work.
I managed to restructure the files, as you suggested, and now the code should work fine.

Cheers
