### ISSUE TITLE
AttributeError: 'int' object has no attribute 'index'

### ISSUE THREAD

**Issue by lisentao** [aimagelab/mcmr#3]
Thank you for sharing your amazing work!   
I'm sorry to bother you.
 I have a problem in main.py in line 640(      g['lr'] = [self.args.G_lr_steps_values[self.args.G_lr_steps.index(self.epoch)]    )
![image](https://user-images.githubusercontent.com/49113628/164951636-65c2c717-f22e-4c3e-8316-3c63ebe97143.png)

In this line, I find all of the self.args.G_lr_steps_values,self.args.G_lr_steps,self.epoch are Integer. So the integer can not use with the function index().Also,when we use [] behind an Integer,there will be an error (   'int' object is not subscriptable  )
I am wondering how to solve this problem,can you give me any suggestions.

**Comment by lisentao** [comment]
I think this is about the learning rate,because g['lr'] = 1e-05.
But when I change the g['lr'] = 1e-05 or other code I found in the website like these
![image](https://user-images.githubusercontent.com/49113628/164967471-9870c604-c324-4376-8c2f-959fbb8c81e1.png)
Now there has problem in the line 845.
![image](https://user-images.githubusercontent.com/49113628/164967554-41202b8d-4e20-43b0-8ffa-9062f482d391.png)
![image](https://user-images.githubusercontent.com/49113628/164967625-d2abc186-b633-4a3c-b180-3fa1190e1cce.png)
I have run the code on GeForce RTX 3060 with Cuda11.1  .   
I am sure these environment can run pytorch code with GPU because I can train the code of MVSNet-pytorch in these environment. And all of the last code run well.
![image](https://user-images.githubusercontent.com/49113628/164967765-b283d5e5-3987-4b3a-b56d-f615d825e994.png)
The last image is the instruction about how the test on Pascal 3D
![image](https://user-images.githubusercontent.com/49113628/164968041-47c7e0f9-995a-4753-a24e-b555cba119bf.png)
And the last image is what I run.
![image](https://user-images.githubusercontent.com/49113628/164968168-bc6d00c1-2707-4ee9-a805-667d852c11cc.png)
I wonder where did I go wrong.Can you give me some suggestions.
Thanks for your listening.

**Comment by alexj94** [comment]
Hi,
thanks for your interest in our work.
Regarding the first problem, the parameters _self.G_lr_steps_ and _self.G_lr_steps_values_ should be two lists in which the first one has the decay epochs (e.g. [50, 150]) and the second one the values of the learning rate (e.g. [1e-4, 1e-5]). I modified the _main.py_ file because the initialization of those two parameters was wrong. 
Regarding the second problem, I can see that the terminal error is more related to SoftRasterizer which doesn't have a compatible kernel for your GPU. I modified the _setup_softras.py_ file adding the CUDA version for the new RTX architectures, which includes also your RTX 3060. Try to compile again the SoftRas module.
Thanks for your feedback and let me know if everything works fine.

**Comment by lisentao** [comment]
Thank you for your reply.
In Monday I try to Add '--generate-code=arch=compute_86,code=sm_86', in setup_softras.py and now in can use softras in RTX3060.See in the last image
![image](https://user-images.githubusercontent.com/49113628/165457705-d1c7478e-e977-42ca-bfa4-0a103d49a36c.png)
But there still have the problem of "RuntimeError: CUDA error: an illegal memory access was encountered"
![image](https://user-images.githubusercontent.com/49113628/165455890-0b402470-aaaa-4264-b5ac-9a2f5b00846f.png)
I try to found the reason and I found an Strange phenomenon.I add three lines in your code,we can see in the last image.
![image](https://user-images.githubusercontent.com/49113628/165456297-deb32545-7dd7-4415-8a57-31b772c17d80.png)
And I get the result like in the last image
![image](https://user-images.githubusercontent.com/49113628/165456479-ad5e6874-c99f-4916-8957-4bc015d2aa13.png)
The problem occur in the function torch.cat().  I add the line "out_a = out_a.cuda()" and get the same result.
![image](https://user-images.githubusercontent.com/49113628/165456756-25259999-6e87-4f7d-b26c-070e68959943.png)
When I was discouraged, I made a small attempt, but it worked.We can see in the last image about what I got.
![image](https://user-images.githubusercontent.com/49113628/165457155-abd512af-5b40-461e-8b1b-9f8bc139edeb.png)
All six parameters,I transform to .cpu(),and then transform to .cuda(), and in the last,I get it.
![image](https://user-images.githubusercontent.com/49113628/165457418-467e9176-da10-4981-b80e-911f9c4865eb.png)
I really don not now why.It's a really amazing question.

**Comment by lisentao** [comment]
And now I have the problem about the result.
I think the bottle in PASCAL 3D get good result.We can see the last three picture.
![image](https://user-images.githubusercontent.com/49113628/165458624-437be94c-3453-418f-91a6-b058e1495368.png)
![image](https://user-images.githubusercontent.com/49113628/165458625-7219557c-8b40-40d1-acfb-054916d276d2.png)
![image](https://user-images.githubusercontent.com/49113628/165458683-06cf0c9e-881b-4472-9f91-b8dca1ec6eef.png)
But the problem occur when I try to run the boat in PASCAL 3D dataset.
I have now run the boat dataset, and we can see the result in the last three picture
![image](https://user-images.githubusercontent.com/49113628/165458927-23700118-f2d1-47bf-aa13-8e9002eb3d51.png)
![image](https://user-images.githubusercontent.com/49113628/165461668-c0386a06-6cc0-4db5-9d28-d3077db45feb.png)
![image](https://user-images.githubusercontent.com/49113628/165461958-616fb30c-d82f-4eef-a05b-96f1073046e4.png)
The result like these
![image](https://user-images.githubusercontent.com/49113628/165459421-8b864445-cd99-4510-93db-f3721f56f802.png)
![image](https://user-images.githubusercontent.com/49113628/165459450-af922c8c-1da1-4cd4-9e50-e07c0ca5d32d.png)
I am wondering why this happen.
At first, I find a lot of False in there,we can see in the last image
![image](https://user-images.githubusercontent.com/49113628/165460300-277d68ec-6d19-4f38-8de5-f6c9a0cbd922.png)
So I set lots of parameters ot True.We can see in the last image.
![image](https://user-images.githubusercontent.com/49113628/165460477-3f30006b-0d04-41dc-9e88-26bb2519b13c.png)
And it does not work.
Then I found the problem of g['lr'].We can see in the last image
![image](https://user-images.githubusercontent.com/49113628/165460874-788b0ec9-956b-422e-a556-7c51a791b8e1.png)
![image](https://user-images.githubusercontent.com/49113628/165461005-ad6093ee-8a45-4535-8482-61ca2893bf6e.png)
The self.args.G_lr_steps = 351 but it's only did it once.Is that what caused the problem.Do you have any suggestions.
Thank you for listening to my long speech.

**Comment by alexj94** [comment]
@lisentao are you using pre-trained weights? If so, which weights are you using?

**Comment by lisentao** [comment]
I am using this pretrained weight
![image](https://user-images.githubusercontent.com/49113628/165469909-c69d5c3f-510f-414e-830d-8fc90350f089.png)

**Comment by alexj94** [comment]
If you're using those weights you should test on all Pascal3D+ classes using the same arguments contained in the "args" field of the weight files. We do not run experiments on just the boat class. 
Regarding the learning rate problem, if you update the code with the last changes, it should work fine.

**Comment by lisentao** [comment]
I am very appreciate for your reply,I will try.
