### ISSUE TITLE
how to test with my own picture

### ISSUE THREAD

**Issue by lisentao** [aimagelab/mcmr#4]

**Comment by lisentao** [comment]
I am interested with your work, it is wonderful, and I want to use a picture to test this network to directly generate output (such as .ply files or .obj files). Do you have  any opinions.

**Comment by AlbertoRemus** [comment]
>  to directly generate output (such as .ply files or .obj files)

Hi @lisentao this modification did the job for me:

https://github.com/AlbertoRemus/mcmr/commit/7e9bd74f12da19e28365d0f2ba77bc3ec3648d9e

![Screenshot from 2022-05-03 14-58-47](https://user-images.githubusercontent.com/54797872/166457675-51e1303c-9f30-4d3a-8dca-c2826bf71228.png)

**Comment by lisentao** [comment]
Thank you very much.@AlbertoRemus
